### ISSUE TITLE
Error running the theme in WSL

### ISSUE THREAD

**Issue by cohan8999** [projekt0n/caret.nvim#1]
Hi,

Installing and running the theme seems to work fine in WIndows, but on WSL I get the following error:

```
Error detected while processing /home/lasse/.config/nvim/plugged/caret.nvim/colors/caret.vim:
line    1:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
E5108: Error executing lua /home/lasse/.config/nvim/plugged/caret.nvim/lua/caret.lua:569: attempt to index field 'cmd' (a function value)
stack traceback:
        /home/lasse/.config/nvim/plugged/caret.nvim/lua/caret.lua:569: in function 'setup'
        [string ":lua"]:1: in main chunk
```
        
With that being said, the theme seems to be working fine except for throwing this error.

**Comment by ful1e5** [comment]
@cohan8999 It appears there is a problem with the `vim.cmd.colorschme('caret')` line, which is used for changing the colorscheme. The `vim.cmd.colorscheme` syntax is not available in the early release of Neovim 0.7, I suppose. Additionally, we are explicitly defining the colorscheme anyway (as documented). This line should be removed. I forgot to remove this line before the release, but I will patch that soon.
